// User Details

export const GET_USER_DETAILS = 'GET_USER_DETAILS';
export const GET_USER_DETAILS_SUCCESS = 'GET_USER_DETAILS_SUCCESS';
export const GET_USER_DETAILS_FAILURE = 'GET_USER_DETAILS_FAILURE';

//Panet Data
export const GET_PLANET_DATA = 'GET_PLANET_DATA';
export const GET_PLANET_DATA_SUCCESS = 'GET_PLANET_DATA_SUCCESS';
export const GET_PLANET_DATA_FAILURE = 'GET_PLANET_DATA_FAILURE';

// Logout
export const LOGOUT_USER = 'LOGOUT_USER';
